# Generated by Django 3.0.7 on 2020-06-23 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assigment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('submit_num', models.IntegerField()),
                ('num', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='homework',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hw_photo', models.ImageField(upload_to='')),
                ('submit_time', models.DateTimeField()),
                ('whether_submit', models.BooleanField()),
                ('whether_correct', models.BooleanField()),
                ('remark', models.TextField()),
                ('score', models.CharField(max_length=10)),
                ('assigment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.assigment')),
            ],
        ),
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='spciality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.school')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homework.school')),
                ('spciality', models.ManyToManyField(to='homework.spciality')),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('class_f', models.CharField(max_length=50, null=True)),
                ('selfinfo', models.TextField()),
                ('sexuality', models.CharField(max_length=50, null=True)),
                ('age', models.IntegerField()),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homework.school')),
                ('spciality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homework.spciality')),
                ('subject', models.ManyToManyField(to='homework.subject')),
            ],
        ),
        migrations.CreateModel(
            name='score_report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_score', models.CharField(max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.subject')),
            ],
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.homework')),
            ],
        ),
        migrations.AddField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.student'),
        ),
        migrations.AddField(
            model_name='assigment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.subject'),
        ),
    ]
