# Generated by Django 3.0.7 on 2020-06-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='hw_photo',
        ),
        migrations.AlterField(
            model_name='assigment',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='assigment',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='assigment',
            name='submit_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='assigment',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='submit_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='whether_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='homework',
            name='whether_submit',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='selfinfo',
            field=models.TextField(null=True),
        ),
    ]
