# Generated by Django 3.0.7 on 2020-06-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_auto_20200623_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='imagepath',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='photo',
        ),
    ]
